version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map the container's port 8000 to the host's port 8000
    volumes:
      - .:/app  # Mount your project directory into the container
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]